baseURL = "https://heatherheine.github.io/"
languageCode = "en-us"
title = "Heather Heine | Biotech Entrepreneur & Innovator"
theme = "typo"

# GitHub Pages can publish from /docs folder
publishDir = "docs"

[params]
  # Brief professional tagline
  subtitle = "MD/PhD Biotechnologist & Entrepreneur"
  
  # Force dark mode (black background)
  theme = "dark"

  # Social media links
  [[params.social]]
    name = "x"
    url = "https://x.com/heatherheine"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/heatherheine"

# Main menu configuration
  [[params.menu]]
    name = "about"
    url  = "/about"

  [[params.menu]]
    name = "accomplishments"
    url  = "/accomplishments"

